### ISSUE TITLE
NPE in plugin

### ISSUE THREAD

**Issue by beansoft** [beansoftapp/flutter-storm-support#19]
java.lang.Throwable: filtered path list is empty
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.ixigua.completion.contributor.AssetLiteralCompletionContributor.assetsForPrefix(AssetLiteralCompletionContributor.java:85)
	at com.ixigua.completion.contributor.AssetLiteralCompletionContributor.access$100(AssetLiteralCompletionContributor.java:28)
	at com.ixigua.completion.contributor.AssetLiteralCompletionContributor$1.addCompletions(AssetLiteralCompletionContributor.java:49)

**Comment by beansoft** [comment]
fixed in 2020.3.2
