### ISSUE TITLE
Exception thrown when creating new Flutter project

### ISSUE THREAD

**Issue by BMSihlas** [beansoftapp/flutter-storm-support#38]
## What happened

Tried creating new flutter project from scratch using the New Project dialog and the plugin Flutter Storm.

I left the already filled values and moved on to create project. Though the project was successfuly created in the specfified location, the editor threw the exception found below.

## Version information

PhpStorm `2023.1.3` • Flutter Storm plugin `com.github.beansoftapp.flutter.storm 2023.1.0` • Dart plugin `231.9161.14`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException: Cannot invoke "io.flutter.sdk.FlutterSdk.queryFlutterChannel(boolean)" because "sdk" is null
	at io.flutter.module.settings.PlatformsForm.initChannel(PlatformsForm.kt:31)
	at io.flutter.module.settings.FlutterCreateAdditionalSettingsFields.lambda$addSettingsFields$3(FlutterCreateAdditionalSettingsFields.java:153)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by beansoft** [comment]
Reproduced, if this is the first time when creating a project, it will happen, and will not happen again in the following project creation. I'll try to fix it.

**Comment by beansoft** [comment]
It should be fixed in the 2023.2 version of the plugin, please try and test it(however, the new plugin only supports PhpStorm 2023.2).
