### ISSUE TITLE
Exception on deprecated feature

### ISSUE THREAD

**Issue by adlandh** [beansoftapp/flutter-storm-support#41]
Version information
GoLand 2024.1 • Flutter Storm plugin com.github.beansoftapp.flutter.storm 2023.2.0 • Dart plugin 241.14768

No Flutter sdk configured.

Exception
null

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.DeviceSelectorAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.beansoftapp.flutter.storm]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by beansoft** [comment]
Thanks for your report, I'm going to fix it this weekend.

**Comment by beansoft** [comment]
Hi, I've uploaded a new version: https://plugins.jetbrains.com/files/14718/522809/flutter-storm.zip

I've tested it under GoLand 2024.1, please check if it also works for you.

**Comment by adlandh** [comment]
So far so good. Thank you.
